services:
  chanchito:
    build: . # Build the Dockerfile in the current directory
    ports:
      - "3000:3000"
    depends_on:
      - monguito
    
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: